version: "3.8"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes:
      - mongo_data:/data/db
  server:
    build: ./server
    image: book-list:latest
    container_name: book-list-server
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./server:/app
    depends_on:
      - mongo_db

volumes:
  mongo_data: 
